spring:
  datasource:
    url: jdbc:mysql://121.172.118.190:3306/travelmate
    username: developer2
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ZJHdk45nvEJGwrj3MneJND8rhgiF39vNSjRUGOWUdn4=
  expiration: 3600000 # 1시간